version: '3.8'

services:
  server:
    image: ${BLNK_IMAGE:-jerryenebeli/blnk:v0.6.2}
    container_name: server
    restart: on-failure
    environment:
      TZ: ${TZ:-Etc/UTC}
    ports:
      - "5001:5001"
      - "80:80"
      - "443:443"
    depends_on:
      - redis
      - postgres
    volumes:
      - ./blnk.json:/blnk.json

  worker:
    image: ${BLNK_IMAGE:-jerryenebeli/blnk:v0.6.2}
    container_name: worker
    restart: on-failure
    entrypoint: [ "./blnk", "workers"]
    depends_on:
      - redis
      - postgres
    volumes:
      - ./blnk.json:/blnk.json

  migration:
    image:  jerryenebeli/blnk:v0.6.2
    entrypoint: [ "./blnk", "migrate","up" ]
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./blnk.json:/blnk.json

  redis:
    image: redis:7.2.4
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: ${POSTGRES_IMAGE:-postgres:latest}
    container_name: ${POSTGRES_CONTAINER:-postgres}
    restart: on-failure
    ports:
      - "${POSTGRES_OUTER_PORT:-5432}:5432"
    environment:
      TZ: ${TZ:-Etc/UTC}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-blnk}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  typesense:
    image: typesense/typesense:0.23.1
    container_name: typesense
    command: ["--data-dir", "/data", "--api-key=blnk-api-key", "--listen-port", "8108"]
    volumes:
      - typesense_data:/data
    ports:
      - "8108:8108"

  directus:
    image: ${DIR_IMAGE:-directus/directus:latest}
    container_name: directus
    ports:
      - ${DIR_OUTER_PORT:-8055}:8055
    volumes:
      - uploads:/directus/uploads
    environment:
      TZ: ${TZ:-Etc/UTC}
      KEY: ${DIR_KEY:-anykey}
      SECRET: ${DIR_SECRET:-anysecret}
      ADMIN_EMAIL: ${DIR_ADMIN_EMAIL:-admin@demo.com}
      ADMIN_PASSWORD: ${DIR_ADMIN_PASSWORD:-adminpassword}
      WEBSOCKETS_ENABLED: true
      DB_CLIENT: 'pg'
      DB_HOST: ${POSTGRES_CONTAINER:-postgres}
      DB_PORT: ${POSTGRES_INNER_PORT:-5432}
      DB_DATABASE: ${POSTGRES_DB:-blnk}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_PASSWORD: ${POSTGRES_PASSWORD:-password}
      DB_SEARCH_PATH: ${POSTGRES_SCHEMA:-blnk}

volumes:
  pg_data:
  typesense_data:
  uploads:
