version: '3.8'

services:
  typesense:
    image: typesense/typesense:0.23.1
    container_name: typesense
    command: ["--data-dir", "/data", "--api-key=blnk-api-key", "--listen-port", "8108"]
    volumes:
      - typesense_data:/data
    ports:
      - "8108:8108"
    logging:
      driver: "none"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8108/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blnk
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  server:
    build: .
    restart: on-failure
    ports:
      - "5001:5001"
      - "80:80"
      - "443:443"
    depends_on:
      - redis
      - postgres
      - typesense
    volumes:
      - ./blnk.json:/blnk.json

  worker:
    build: .
    restart: on-failure
    entrypoint: [ "./blnk", "workers"]
    depends_on:
      - redis
      - postgres
      - typesense
    volumes:
      - ./blnk.json:/blnk.json

  migration:
    build: .
    entrypoint: [ "./blnk", "migrate","up" ]
    restart: on-failure
    depends_on:
      - postgres
    volumes:
      - ./blnk.json:/blnk.json



volumes:
  pg_data:
  typesense_data:

